name: Test-CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.16.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go
      - name: Build Code
        run: |
          go build -o program main.go
      
