name: Release Charts

on:
  push:
    paths:
      - 'charts/v1beta1/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CR_PACKAGE_PATH: charts/v1beta1/*/
          CR_RELEASE_NOTES: CHANGELOG.md
          # CR_RELEASE_NAME_TEMPLATE: "{{ .Name }}-{{ .Version }}-dev"
